### ISSUE TITLE
[Question] Supervisor auto-update 

### ISSUE THREAD

**Issue by oliverhavrila** [ketilmo/balena-ads-b#100]
Hello,

Just for today, 5 new versions for supervisor have been released from 16.2.10 to 16.2.15.

Is it possible to set somehow automatic update for supervisor? Or at least e.g. an email notification?

Thank you very much

**Comment by ketilmo** [comment]
Hi @oliverhavrila,

Thanks for reaching out. See the following balena forums thread for more information about this topic: https://forums.balena.io/t/automated-os-and-supervisor-updates/359033.

Also, see the **autohupr** tool that's mentioned in the thread in question: https://github.com/balena-labs-projects/autohupr.

If you would like more information about the balena supervisor, I would recommend you contact balena directly.
