### ISSUE TITLE
Update WingBits

### ISSUE THREAD

**Issue by serviceman77** [ketilmo/balena-ads-b#101]
Hello. I read that Wingbits has a mandatory update needed within the next 14 days. Will you be updating the container to the new script? Thanks

**Comment by ketilmo** [comment]
Thanks for the heads up! Do you have some more information about this?

**Comment by serviceman77** [comment]
https://discord.com/channels/1082294632689455154/1087693013112848424/1243574165278163085

**Comment by ketilmo** [comment]
Hi @serviceman77,

Wingbits feeding is now updated to config version 0.0.4.
