### ISSUE TITLE
Plane finder setup instructions doesn't work... Get error

### ISSUE THREAD

**Issue by shawaj** [ketilmo/balena-ads-b#107]
The instructions describes how to get a sharecode for plane finder but when you click to generate the share code it goes to a balena error page...
![Screenshot_20240601_224150_Chrome](https://github.com/ketilmo/balena-ads-b/assets/3359418/4801b340-07dd-40ca-aaab-3475a885d84f)

I guess the device is hosted on balena but the public URL has been toggled off?

**Comment by shawaj** [comment]
Actually just discovered you can do issue command:

`pfclient`

On command line. And then access the sharecode creation page via port 30053 on a local device. 

@ketilmo shall I just update the docs to reflect that?

**Comment by ketilmo** [comment]
That’s very strange. Do you get this error after extracting the contents of the SharecodeGenerator.zip file and punching the receiver details in the web UI? The posting of the details should go straight to the PlaneFinder servers.

That said, if you have found a way to do this directly through the command line, nothing is better. So yes, please share the details. :)

**Comment by shawaj** [comment]
The contents of planefinder sharecode generator HTML seems to link on the form to a balena device...

https://github.com/ketilmo/balena-ads-b/blob/2dfc53b9870e27e1447806759d05bb571acc5c0d/planefinder/SharecodeGenerator.html#L76-L100

Cool I'll update the docs to explain how to do it from the device itself.

**Comment by shawaj** [comment]
![pf1](https://github.com/ketilmo/balena-ads-b/assets/3359418/abe4086a-c5f4-42b5-a502-6b521e2a2d84)
![pf2](https://github.com/ketilmo/balena-ads-b/assets/3359418/d979fec7-b92f-40d7-a379-09bc070c67cc)
![pf3](https://github.com/ketilmo/balena-ads-b/assets/3359418/0958fc1f-2374-4e67-89ca-65a01a6e5b85)
![pf4](https://github.com/ketilmo/balena-ads-b/assets/3359418/cc218a38-a33a-4f13-b4c6-04f69dbbfb98)
![pf5](https://github.com/ketilmo/balena-ads-b/assets/3359418/7d3ef684-0918-408f-8029
[bootstrap.min.zip](https://github.com/user-attachments/files/15525709/bootstrap.min.zip)
-072c581b4c12)

Just posting these here for reference

**Comment by ketilmo** [comment]
> The contents of planefinder sharecode generator HTML seems to link on the form to a balena device...
> 
> https://github.com/ketilmo/balena-ads-b/blob/2dfc53b9870e27e1447806759d05bb571acc5c0d/planefinder/SharecodeGenerator.html#L76-L106
> 
> Cool I'll update the docs to explain how to do it from the device itself.

I investigated a bit, and believe the form action specified in the source is just a placeholder. The actual call is made using an ajax JavaScript call. It still works for me the old way in Chrome. Anyway – your approach sounds cleaner.

**Comment by shawaj** [comment]
Oh weird. I was doing it on my phone initially so perhaps that's the issue... Probably Chrome on the phone being crappy or something and not loading the JS correctly

**Comment by shawaj** [comment]
I checked and it's definitely something to do with phone browser not properly loading the CSS and JS from the subfolder from the relative links. The zip file way worked fine on my laptop.

**Comment by ketilmo** [comment]
Thanks for checking and confirming, @shawaj! Glad to hear that.
