### ISSUE TITLE
[QUESTION] Updating using blue button is not working

### ISSUE THREAD

**Issue by winiberto** [ketilmo/balena-ads-b#108]
i'm trying to update to new version but when I use the blue button it's always in "loading mode". 

![image](https://github.com/ketilmo/balena-ads-b/assets/16902313/c12716c1-15c6-448f-aea8-c6c715e06826)

**Comment by ketilmo** [comment]
Hi @winiberto,

Thanks for reaching out. The build process typically takes a few minutes but might take longer under certain circumstances. If you click the red `0.0.0+rev2` link (visible in your screenshot), you will see a status log of what's happening. You can also try clicking the blue balena button again to trigger a new build.

Good luck! Let us know if it works for you!

**Comment by shawaj** [comment]
I just tried this to update to latest and it worked for me :-)

**Comment by winiberto** [comment]
Hi @ketilmo @shawaj I tried it about 4 days ago, then tried again yesterday. After two hours I decided to delete the two attempts and try again. It worked. Thank  you for the support.

**Comment by shawaj** [comment]
@winiberto I have found with balena, sometimes it can get stuck in the build process but it never times out. I think it's a bug in their builder. It only seems to happen periodically but still very annoying when it does!

**Comment by ketilmo** [comment]
Thanks for the update, @winiberto! Happy feeding. Don't hesitate to reach out if you have any further questions.
