### ISSUE TITLE
Add app to https://hub.balena.io/

### ISSUE THREAD

**Issue by xginn8** [ketilmo/balena-ads-b#11]
There are instructions for compatibility here: https://www.balena.io/blog/introducing-balenahub-an-easier-way-to-find-and-publish-apps-and-projects-for-edge-devices/, let me know if i can help at all!

**Comment by ketilmo** [comment]
Thanks for reaching out, @xginn8! I belive I have added the necessary metadata to balena.yml. Let me know if I'm missing something. Thanks for your help!

**Comment by ketilmo** [comment]
It’s live now, so I’m closing this ticket. Thanks!
