### ISSUE TITLE
[Feature Request] Add support for disabling all services

### ISSUE THREAD

**Issue by ketilmo** [ketilmo/balena-ads-b#126]
Currently, it's only possible to (cleanly) disable the services maintained by this project. It would be nice to be able to do that to _all_ services, including `kiosk` and `wifi-connect`.

The following balena feature request is related: [Add option to permanently stop/disable containers](https://feature-requests.balena.io/posts/42/add-option-to-permanently-stop-disable-containers)

**Comment by Teko012** [comment]
I thought about this as well, it should be fairly easy to implement. I think we just need a super small image with curl, and a short bash script that runs 1 or 2 curl calls, then also shuts itself down.

**Comment by shawaj** [comment]
Are those services using balena blocks?

**Comment by Teko012** [comment]
Yes, but we build it ourselves

**Comment by shawaj** [comment]
If building ourselves, can't we edit a couple files and just leave the others as upstream? 

But maybe a service container better as can then handle #127 as well in same container I guess 🤔

**Comment by Teko012** [comment]
I don't think we can easily mix between them. In the kiosk we just add some packages to something they have already built. Probably a service container is better. But changing the restart policy somewhat already solved this problem, if you stop it once manually, it won't restart.

**Comment by shawaj** [comment]
Could just add a small start.sh script here... https://github.com/ketilmo/balena-ads-b/blob/master/kiosk/Dockerfile.template

Which just has the ingestion of disabled services env variable and the curl command to disable? And then just does the standard start procedure? 

But that's assuming not going down the service container route which is likely better I guess

**Comment by Teko012** [comment]
Technically we could probably replace the wifi as well similarly with their prebuilt docker image, and then do the modification. There is no real reason for us to build the whole thing.

**Comment by shawaj** [comment]
It might help to solve #129 as well by doing it that way instead of submodules...

**Comment by Teko012** [comment]
Yes, technically with https://github.com/ketilmo/balena-ads-b/pull/130, we should be able to modify both a little bit, and add an option to disable it and quit.

**Comment by ketilmo** [comment]
Great discussion! Let me know if you need anything from me here.
