### ISSUE TITLE
[Feature Request] Implement dump978-fa UAT Support

### ISSUE THREAD

**Issue by ketilmo** [ketilmo/balena-ads-b#13]

**Comment by ketilmo** [comment]
Hi everyone,

This item is in progress. It's not possible to test UAT here, so I'm collaborating with a couple of persons in the US for this. I will update this ticket as soon as I have news.

Kind regards,
Ketil

**Comment by jason0x21** [comment]
Are you still getting enough US help with this?  If not let me know.  My existing rig (that I'm planning on converting to balena-ads-b), has a working dual-receiver setup.

**Comment by JPGMC** [comment]
Hello, if you can share the instructions, it would be great. I am upgrading to the latest version and trying to figure out how to configure UAT since we don't have access to systemctl in the container. Any tips appreciate.

**Comment by ketilmo** [comment]
Hi @JPGMC,

Certainly! It's been tested by several persons now and will be released here soon. But if you want to try it straight away, feel free to contact me directly here: https://ketil.mo.land/contact

**Comment by ketilmo** [comment]
This feature has now been implemented. 🥳 Please refer to the documentation for details: https://github.com/ketilmo/balena-ads-b#part-9--configure-uat-optional-and-us-only
