### ISSUE TITLE
Write Error /usr/bin/taskset: no space left on device

### ISSUE THREAD

**Issue by lrehmann** [ketilmo/balena-ads-b#131]
Setup wasn't progressing with errors for the images being installed
`Failed to download image 'registry2.balena-cloud.com/v2/*** due to 'failed to register layer: Error processing tar file(exit status 1): write /usr/bin/taskset: no space left on device'`
Had a 16GB micro SD card, but according to df -h, it appeared belana didn't setup the partitions correctly

Unplug and plug back in solved -- partitions were resized and installation is progressing

**Comment by ketilmo** [comment]
Thanks for reporting this, @lrehmann! I'm happy to hear that you were able to sort it out.
