### ISSUE TITLE
Some containers that are missing required settings still need to keep running

### ISSUE THREAD

**Issue by ketilmo** [ketilmo/balena-ads-b#133]
A case I didn't consider when merging #123 is that some services need the user to interact with the service's shell to register an account. To keep it clean and maintainable, I suggest we pause for missing settings and shut down when a service is specifically disabled through `DISABLED_SERVICES`.

Thoughts, @Teko012 and @shawaj?

**Comment by Teko012** [comment]
We could remove it from the parts where it's not disabled, is that what you are suggesting?

**Comment by shawaj** [comment]
yeah could just remove it for when they aren't explicitly disabled?

or just add a wait period so that when they are not explicitly disabled it will wait like 1 hour or something before disabling? but maybe that is overkill i dunno...and might confuse people.

**Comment by Teko012** [comment]
Should fix this too: https://github.com/ketilmo/balena-ads-b/pull/137
