### ISSUE TITLE
Bad Gateway

### ISSUE THREAD

**Issue by Samuel20354** [ketilmo/balena-ads-b#15]
So i have set up the abs flight tracker on balena cloud everything is setup up but when i try to access the web page it says Bad Gateway thats all 

Thanks

**Comment by ketilmo** [comment]
Hi @Samuel20354, thanks for reaching out!

What webpage are you trying to access? Is it the local device, as outlined in [Step 8](https://github.com/ketilmo/balena-ads-b/blob/master/README.md#part-8--exploring-flight-traffic-locally-on-your-device) in the documentation?

Also, what device are you running on?

**Comment by Samuel20354** [comment]
Hi thanks @ketilmo but I no longer need help I have now made my rpi (raspberry pi) run pi-hole

Thanks

**Comment by ketilmo** [comment]
@Samuel20354 That's noted! Let us know if you give it another try in the future. :)
