### ISSUE TITLE
Wingbits URL

### ISSUE THREAD

**Issue by Teko012** [ketilmo/balena-ads-b#152]
I'm not familiar with wingbits too much, but this [URL](https://github.com/ketilmo/balena-ads-b/blob/master/wingbits/wingbits_installer.sh#L9) in the install script doesn't exist anymore.

**Comment by shawaj** [comment]
@Teko012 I think that can be removed actually. It was the old install script I believe

**Comment by shawaj** [comment]
Confirmed... https://vector.dev/highlights/2023-11-07-new-linux-repos/

**Comment by ketilmo** [comment]
Thank you so much! Looks go to me!
