### ISSUE TITLE
[Feature Request] Add ADS-B Exchange

### ISSUE THREAD

**Issue by craftbyte** [ketilmo/balena-ads-b#22]
Any change we could see ADS-B exchange being added to the sending containers? It supports dump1090. 

Instructions: https://www.adsbexchange.com/how-to-feed/

**Comment by RuudOskam** [comment]
Good request, i agree with you.. ADS-B exchange added would be great!

**Comment by ketilmo** [comment]
Hi @craftbyte and @RuudOskam,

I'm happy to report that we now have support for ADSB Exchange thanks to the following pull request from @garethhowell (inspired by code from @marcelstoer): #20

A big thanks to the guys for providing this. Enjoy the feeding of yet another network! :) 

Kind regards,
Ketil

**Comment by ketilmo** [comment]
This issue duplicates #14

**Comment by RuudOskam** [comment]
Wow that is great! THANKS  Ketil..
