### ISSUE TITLE
repos/balena-io/wifi-connect has moved, causing build error.

### ISSUE THREAD

**Issue by drewgolden** [ketilmo/balena-ads-b#27]
curl https://api.github.com/repos/balena-io/wifi-connect/releases/latest -s 
{
  "message": "Moved Permanently",
  "url": "https://api.github.com/repositories/37727198/releases/latest",
  "documentation_url": "https://docs.github.com/v3/#http-redirects"
}

**Comment by ketilmo** [comment]
Hi @drewgolden,

Thanks for engaging in balena ADS-B. Were you able to build the repository without any error messages?

Kind regards,
Ketil

**Comment by drewgolden** [comment]
I just branched and removed wifi-connect from the docker compose to get the
build to work for me.


---
Drew Golden

**Comment by ketilmo** [comment]
With help from Anders in the community, I was able to reproduce and solve this issue. It turns out the wifi-connect repo's URL was changed. Now everything should work fine again. Thanks to @drewgolden for reporting this and to Anders for supplying the fix.
