### ISSUE TITLE
Port 30106 for FA MLAT Results isn´t reachable

### ISSUE THREAD

**Issue by DanBuBerlin** [ketilmo/balena-ads-b#29]
Hi @ketilmo,

can you also put the port 30106 in the ports list, please? 30106 is normally the FA MLAT results port. With VRS you get from there the MLAT-data in Basestation-format.

See here: https://discussions.flightaware.com/t/vrs-show-both-dump1090-adsb-and-fa-mlat-positions/17399

From my other receivers I pull 30005 an 30106 to VRS.

Greetings from Berlin

Daniel

**Comment by ketilmo** [comment]
Hi @DanBuBerlin,

Thanks for your request. This is a very minor change, so I have now added it to the service. Please redeploy and confirm that it works as expected. 

Kind regards,
Ketil
