### ISSUE TITLE
Balena release failing repeatedly [SOLVED]

### ISSUE THREAD

**Issue by Roundhead22** [ketilmo/balena-ads-b#35]
Im unable to create a banela release the reason it fails is 
![B4CD723F-57F6-43EC-989C-2AFE02494DC7](https://user-images.githubusercontent.com/92760172/137810595-807bfbdb-9ecb-48b0-b908-f5b8af320246.png)

I have tried to create a release 4 plus times and same error occurs

**Comment by ketilmo** [comment]
Hi @Roundhead22,

Thanks for reporting this issue. It was caused by an update in one of the upstream dependencies, and has now been fixed.

**Comment by ketilmo** [comment]
Solved by #05cc32c
