### ISSUE TITLE
Newbe Issue at Point 14

### ISSUE THREAD

**Issue by Houseman666** [ketilmo/balena-ads-b#48]
Hi together,
sorry I am very new to this space and I dont know excatly how it works here. I tried to set up the balena ads b project but unfortunately I can't get any further at point 14. Maybe you can help me? My powershell gives me an error message that the term "git" is not recognized as a name of a cmdlet, function, script file, or executable program. See Screenshot. I already installed a newer version of powershell (7.2.1) and i tried also install poshGit module. What I am doing worng? 
Thanks in advance for your help! 

![image](https://user-images.githubusercontent.com/99950272/154636596-7e2e7fdc-8878-4d1c-95e1-f7db11bb2c23.png)

**Comment by ketilmo** [comment]
Hi @Houseman666,

I'm not very familiar with the Windows version of Git, but I would recommend trying to download this version: https://git-scm.com/download/win

If you don't need to change the balena-ads-b source, I would consider using the blue "Deploy with balena"-button found here: https://github.com/ketilmo/balena-ads-b#part-2--setup-balena-and-configure-the-device. It's a lot simpler.
