### ISSUE TITLE
How to update to latest version

### ISSUE THREAD

**Issue by Placemaster** [ketilmo/balena-ads-b#52]
Hi,

I am running this system for over a year and would like to update to the latest version so that adsbexchange will be included. This because I use adsbexchange a lot for tracking flight around my home. I cannot find the correct way to do an update. Of course I do not want to lose all my settings. I cannot find the blue button and balena push is not working as it is not complete.
Is there an easy way of updating available. I am running on a Raspberry Pi 3. The current release I am running is : cd2c1cd.
I did update the BalenaOS and the supervisor. BalenaOS is now 2.98.12. Supervisor is 13.1.6.
Thanks for the help, much appreciated.

**Comment by Placemaster** [comment]
I did find the answer in the newsletter. 

How to update?
Updating is easy. If you installed balena-ads-b using the blue Deploy with balena-button, you can click it again and overwrite your current application. All settings will be preserved. You can even do it from this newsletter:

https://dashboard.balena-cloud.com/deploy?repoUrl=https://github.com/ketilmo/balena-ads-b&defaultDeviceType=raspberrypi4-64

**Comment by ketilmo** [comment]
Hi @Placemaster,

Great to hear that you found the guide. I will add it to the project Readme asap.
