### ISSUE TITLE
Flightradar24 requiring MLAT to be disabled on custom receivers

### ISSUE THREAD

**Issue by schubydoo** [ketilmo/balena-ads-b#54]
Just received an email from Flightradar24. They are asking for all receivers (that aren't directly from them) to disable MLAT if said receivers are sharing to multiple networks.

https://forum.flightradar24.com/forum/radar-forums/flightradar24-feeding-data-to-flightradar24/213550-disable-mlat-if-sharing-with-other-networks

Is there a balena variable we can set for this?

**Comment by suggestbest** [comment]
You can disable this from the status page of your feeder:

https://*ip-address-of-your-feeder*:8754
- Click "Settings"
- Choose the dropdown to "disable" next to MLAT

[image: image.png]

**Comment by schubydoo** [comment]
Deployed the latest and confirmed MLAT is off.

**Comment by ketilmo** [comment]
Thanks for confirming, @schubydoo!
