### ISSUE TITLE
Issue while trying to configure new device

### ISSUE THREAD

**Issue by AndreiGr** [ketilmo/balena-ads-b#56]
Hello there,

I am trying to configure a new flight feeder from scratch, and I have an issue with the FlightRadar24 config part.
I am currently at 4.B.14: `When asked for your receiver's IP address/hostname, enter dump1090-fa.`

When I try to do that, I get an error saying the value is incorrect, see image below.
![image](https://user-images.githubusercontent.com/10116768/175124227-5f601044-f02a-414d-b252-b6c90c5d94de.png)

Does anyone know what I'm doing wrong and how to fix it? 😁

**Comment by AndreiGr** [comment]
I found the problem.
I was trying to configure the device before my R820T2 arrived, and because of that, I assume dump1090-fa didn't start completely, therefore fr24feed couldn't find it.

I tried again today after I plugged in the receiver, and it worked without problems.

Issue can be closed.

**Comment by ketilmo** [comment]
Thanks for the update, @AndreiGr!
