### ISSUE TITLE
Unable to get MLAT status [CLOSED]

### ISSUE THREAD

**Issue by kg6qdi** [ketilmo/balena-ads-b#58]
hello, I have been using this for a while and for some odd reason I not been able to get MLAT status even thou everything is setup correctly. I am using the balenaCloud setup I followed the directions to the letter and I see the green MLAT status for a few minutes and then it's gone. Any ideas?

Thanks

**Comment by ketilmo** [comment]
Hi @kg6qdi,

Thanks for reaching out. There can be several reasons for the FlightAware MLAT status turning red. Please have a look at the following issue and see if that can help you sort this out: #21. Let us know if you are able to resolve the issue.
