### ISSUE TITLE
ERROR: /start.sh: line 54: Killed [CLOSED]

### ISSUE THREAD

**Issue by SkyDiscovery** [ketilmo/balena-ads-b#59]
On my second feeder, I get this error in a restart loop:

> 12.07.22 16:21:39 (+0200)  dump1090-fa  Verifying settings...
12.07.22 16:21:39 (+0200)  dump1090-fa   
12.07.22 16:21:41 (+0200)  dump1090-fa  Receiver latitude is set: XX.XXX
12.07.22 16:21:41 (+0200)  dump1090-fa  Receiver longitude is set: XX.XXX
12.07.22 16:21:41 (+0200)  dump1090-fa   
12.07.22 16:21:41 (+0200)  dump1090-fa  Settings verified, proceeding with startup.
12.07.22 16:21:41 (+0200)  dump1090-fa   
12.07.22 16:21:41 (+0200)  dump1090-fa  Enabling adaptive gain in dynamic range mode.
12.07.22 16:21:41 (+0200)  dump1090-fa  Tue Jul 12 14:21:41 2022 UTC  dump1090-fa 7.2 starting up.
12.07.22 16:21:41 (+0200)  dump1090-fa  rtlsdr: using device #0: Generic RTL2832U OEM (Realtek, RTL2838UHIDIR, SN 00000001)
12.07.22 16:21:41 (+0200)  dump1090-fa  Found Rafael Micro R820T tuner
12.07.22 16:21:41 (+0200)  dump1090-fa  rtlsdr: tuner gain set to 49.6 dB (gain step 28)
12.07.22 16:21:42 (+0200)  dump1090-fa  adaptive: using 50% duty cycle
12.07.22 16:21:42 (+0200)  dump1090-fa  adaptive: enabled adaptive gain control with gain limits 0.0dB (step 0) .. 58.6dB (step 29)
12.07.22 16:21:42 (+0200)  dump1090-fa  adaptive: enabled dynamic range control, target dynamic range 30.0dB
12.07.22 16:21:42 (+0200)  dump1090-fa  Allocating 4 zero-copy buffers
12.07.22 16:21:42 (+0200)  dump1090-fa  /start.sh: line 54:    13 Killed                  /usr/bin/dump1090-fa $dump1090configuration
12.07.22 16:22:38 (+0200)  dump1090-fa  Verifying settings...
12.07.22 16:22:38 (+0200)  dump1090-fa   
12.07.22 16:22:40 (+0200)  dump1090-fa  Receiver latitude is set: XX.XXX
12.07.22 16:22:40 (+0200)  dump1090-fa  Receiver longitude is set: XX.XXX
12.07.22 16:22:40 (+0200)  dump1090-fa   
12.07.22 16:22:40 (+0200)  dump1090-fa  Settings verified, proceeding with startup.
12.07.22 16:22:40 (+0200)  dump1090-fa   
12.07.22 16:22:40 (+0200)  dump1090-fa  Enabling adaptive gain in dynamic range mode.
12.07.22 16:22:40 (+0200)  dump1090-fa  Tue Jul 12 14:22:40 2022 UTC  dump1090-fa 7.2 starting up.
12.07.22 16:22:40 (+0200)  dump1090-fa  rtlsdr: using device #0: Generic RTL2832U OEM (Realtek, RTL2838UHIDIR, SN 00000001)
12.07.22 16:22:41 (+0200)  dump1090-fa  Found Rafael Micro R820T tuner
12.07.22 16:22:41 (+0200)  dump1090-fa  rtlsdr: tuner gain set to 49.6 dB (gain step 28)
12.07.22 16:22:41 (+0200)  dump1090-fa  adaptive: using 50% duty cycle
12.07.22 16:22:41 (+0200)  dump1090-fa  adaptive: enabled adaptive gain control with gain limits 0.0dB (step 0) .. 58.6dB (step 29)
12.07.22 16:22:41 (+0200)  dump1090-fa  adaptive: enabled dynamic range control, target dynamic range 30.0dB
12.07.22 16:22:41 (+0200)  dump1090-fa  Allocating 4 zero-copy buffers
12.07.22 16:22:41 (+0200)  dump1090-fa  /start.sh: line 54:    13 Killed                  /usr/bin/dump1090-fa $dump1090configuration
12.07.22 16:23:46 (+0200)  dump1090-fa  Verifying settings...
12.07.22 16:23:46 (+0200)  dump1090-fa   
12.07.22 16:23:48 (+0200)  dump1090-fa  Receiver latitude is set: XX.XXX
12.07.22 16:23:48 (+0200)  dump1090-fa  Receiver longitude is set: XX.XXX
12.07.22 16:23:48 (+0200)  dump1090-fa   
12.07.22 16:23:48 (+0200)  dump1090-fa  Settings verified, proceeding with startup.
12.07.22 16:23:48 (+0200)  dump1090-fa   
12.07.22 16:23:48 (+0200)  dump1090-fa  Enabling adaptive gain in dynamic range mode.
12.07.22 16:23:49 (+0200)  dump1090-fa  Tue Jul 12 14:23:49 2022 UTC  dump1090-fa 7.2 starting up.
12.07.22 16:23:49 (+0200)  dump1090-fa  rtlsdr: using device #0: Generic RTL2832U OEM (Realtek, RTL2838UHIDIR, SN 00000001)
12.07.22 16:23:49 (+0200)  dump1090-fa  Found Rafael Micro R820T tuner
12.07.22 16:23:49 (+0200)  dump1090-fa  rtlsdr: tuner gain set to 49.6 dB (gain step 28)
12.07.22 16:23:49 (+0200)  dump1090-fa  adaptive: using 50% duty cycle
12.07.22 16:23:49 (+0200)  dump1090-fa  adaptive: enabled adaptive gain control with gain limits 0.0dB (step 0) .. 58.6dB (step 29)
12.07.22 16:23:49 (+0200)  dump1090-fa  adaptive: enabled dynamic range control, target dynamic range 30.0dB
12.07.22 16:23:49 (+0200)  dump1090-fa  Allocating 4 zero-copy buffers
12.07.22 16:23:49 (+0200)  dump1090-fa  /start.sh: line 54:    13 Killed                  /usr/bin/dump1090-fa $dump1090configuration
12.07.22 16:24:55 (+0200)  dump1090-fa  Verifying settings...
12.07.22 16:24:55 (+0200)  dump1090-fa   
12.07.22 16:24:57 (+0200)  dump1090-fa  Receiver latitude is set: XX.XXX
12.07.22 16:24:57 (+0200)  dump1090-fa  Receiver longitude is set: XX.XXX
12.07.22 16:24:57 (+0200)  dump1090-fa   
12.07.22 16:24:57 (+0200)  dump1090-fa  Settings verified, proceeding with startup.
12.07.22 16:24:57 (+0200)  dump1090-fa   
12.07.22 16:24:57 (+0200)  dump1090-fa  Enabling adaptive gain in dynamic range mode.
12.07.22 16:24:57 (+0200)  dump1090-fa  Tue Jul 12 14:24:57 2022 UTC  dump1090-fa 7.2 starting up.
12.07.22 16:24:57 (+0200)  dump1090-fa  rtlsdr: using device #0: Generic RTL2832U OEM (Realtek, RTL2838UHIDIR, SN 00000001)
12.07.22 16:24:57 (+0200)  dump1090-fa  Found Rafael Micro R820T tuner
12.07.22 16:24:57 (+0200)  dump1090-fa  rtlsdr: tuner gain set to 49.6 dB (gain step 28)
12.07.22 16:24:58 (+0200)  dump1090-fa  adaptive: using 50% duty cycle
12.07.22 16:24:58 (+0200)  dump1090-fa  adaptive: enabled adaptive gain control with gain limits 0.0dB (step 0) .. 58.6dB (step 29)
12.07.22 16:24:58 (+0200)  dump1090-fa  adaptive: enabled dynamic range control, target dynamic range 30.0dB
12.07.22 16:24:58 (+0200)  dump1090-fa  Allocating 4 zero-copy buffers
12.07.22 16:24:58 (+0200)  dump1090-fa  /start.sh: line 54:    13 Killed                  /usr/bin/dump1090-fa $dump1090configuration
12.07.22 16:26:04 (+0200)  dump1090-fa  Verifying settings...
12.07.22 16:26:04 (+0200)  dump1090-fa   
12.07.22 16:26:06 (+0200)  dump1090-fa  Receiver latitude is set: XX.XXX
12.07.22 16:26:06 (+0200)  dump1090-fa  Receiver longitude is set: XX.XXX
12.07.22 16:26:06 (+0200)  dump1090-fa   
12.07.22 16:26:06 (+0200)  dump1090-fa  Settings verified, proceeding with startup.
12.07.22 16:26:06 (+0200)  dump1090-fa   
12.07.22 16:26:06 (+0200)  dump1090-fa  Enabling adaptive gain in dynamic range mode.
12.07.22 16:26:06 (+0200)  dump1090-fa  Tue Jul 12 14:26:06 2022 UTC  dump1090-fa 7.2 starting up.
12.07.22 16:26:06 (+0200)  dump1090-fa  rtlsdr: using device #0: Generic RTL2832U OEM (Realtek, RTL2838UHIDIR, SN 00000001)
12.07.22 16:26:06 (+0200)  dump1090-fa  Found Rafael Micro R820T tuner
12.07.22 16:26:06 (+0200)  dump1090-fa  rtlsdr: tuner gain set to 49.6 dB (gain step 28)
12.07.22 16:26:07 (+0200)  dump1090-fa  adaptive: using 50% duty cycle
12.07.22 16:26:07 (+0200)  dump1090-fa  adaptive: enabled adaptive gain control with gain limits 0.0dB (step 0) .. 58.6dB (step 29)
12.07.22 16:26:07 (+0200)  dump1090-fa  adaptive: enabled dynamic range control, target dynamic range 30.0dB
12.07.22 16:26:07 (+0200)  dump1090-fa  Allocating 4 zero-copy buffers
12.07.22 16:26:07 (+0200)  dump1090-fa  /start.sh: line 54:    13 Killed                  /usr/bin/dump1090-fa $dump1090configuration
12.07.22 16:27:12 (+0200)  dump1090-fa  Verifying settings...
12.07.22 16:27:12 (+0200)  dump1090-fa   
12.07.22 16:27:14 (+0200)  dump1090-fa  Receiver latitude is set: XX.XXX
12.07.22 16:27:14 (+0200)  dump1090-fa  Receiver longitude is set: XX.XXX
12.07.22 16:27:14 (+0200)  dump1090-fa   
12.07.22 16:27:14 (+0200)  dump1090-fa  Settings verified, proceeding with startup.
12.07.22 16:27:14 (+0200)  dump1090-fa   
12.07.22 16:27:14 (+0200)  dump1090-fa  Enabling adaptive gain in dynamic range mode.
12.07.22 16:27:14 (+0200)  dump1090-fa  Tue Jul 12 14:27:14 2022 UTC  dump1090-fa 7.2 starting up.
12.07.22 16:27:14 (+0200)  dump1090-fa  rtlsdr: using device #0: Generic RTL2832U OEM (Realtek, RTL2838UHIDIR, SN 00000001)
12.07.22 16:27:14 (+0200)  dump1090-fa  Found Rafael Micro R820T tuner
12.07.22 16:27:15 (+0200)  dump1090-fa  rtlsdr: tuner gain set to 49.6 dB (gain step 28)
12.07.22 16:27:15 (+0200)  dump1090-fa  adaptive: using 50% duty cycle
12.07.22 16:27:15 (+0200)  dump1090-fa  adaptive: enabled adaptive gain control with gain limits 0.0dB (step 0) .. 58.6dB (step 29)
12.07.22 16:27:15 (+0200)  dump1090-fa  adaptive: enabled dynamic range control, target dynamic range 30.0dB
12.07.22 16:27:15 (+0200)  dump1090-fa  Allocating 4 zero-copy buffers
12.07.22 16:27:15 (+0200)  dump1090-fa  /start.sh: line 54:    14 Killed                  /usr/bin/dump1090-fa $dump1090configuration
12.07.22 16:28:20 (+0200)  dump1090-fa  Verifying settings...
12.07.22 16:28:20 (+0200)  dump1090-fa   
12.07.22 16:28:22 (+0200)  dump1090-fa  Receiver latitude is set: XX.XXX
12.07.22 16:28:22 (+0200)  dump1090-fa  Receiver longitude is set: XX.XXX
12.07.22 16:28:22 (+0200)  dump1090-fa   
12.07.22 16:28:22 (+0200)  dump1090-fa  Settings verified, proceeding with startup.
12.07.22 16:28:22 (+0200)  dump1090-fa   
12.07.22 16:28:22 (+0200)  dump1090-fa  Enabling adaptive gain in dynamic range mode.
12.07.22 16:28:22 (+0200)  dump1090-fa  Tue Jul 12 14:28:22 2022 UTC  dump1090-fa 7.2 starting up.
12.07.22 16:28:22 (+0200)  dump1090-fa  rtlsdr: using device #0: Generic RTL2832U OEM (Realtek, RTL2838UHIDIR, SN 00000001)
12.07.22 16:28:23 (+0200)  dump1090-fa  Found Rafael Micro R820T tuner
12.07.22 16:28:23 (+0200)  dump1090-fa  rtlsdr: tuner gain set to 49.6 dB (gain step 28)
12.07.22 16:28:23 (+0200)  dump1090-fa  adaptive: using 50% duty cycle
12.07.22 16:28:23 (+0200)  dump1090-fa  adaptive: enabled adaptive gain control with gain limits 0.0dB (step 0) .. 58.6dB (step 29)
12.07.22 16:28:23 (+0200)  dump1090-fa  adaptive: enabled dynamic range control, target dynamic range 30.0dB
12.07.22 16:28:23 (+0200)  dump1090-fa  Allocating 4 zero-copy buffers
12.07.22 16:28:23 (+0200)  dump1090-fa  /start.sh: line 54:    14 Killed                  /usr/bin/dump1090-fa $dump1090configuration
12.07.22 16:29:29 (+0200)  dump1090-fa  Verifying settings...
12.07.22 16:29:29 (+0200)  dump1090-fa   
12.07.22 16:29:31 (+0200)  dump1090-fa  Receiver latitude is set: XX.XXX
12.07.22 16:29:31 (+0200)  dump1090-fa  Receiver longitude is set: XX.XXX
12.07.22 16:29:31 (+0200)  dump1090-fa   
12.07.22 16:29:31 (+0200)  dump1090-fa  Settings verified, proceeding with startup.
12.07.22 16:29:31 (+0200)  dump1090-fa   
12.07.22 16:29:31 (+0200)  dump1090-fa  Enabling adaptive gain in dynamic range mode.
12.07.22 16:29:31 (+0200)  dump1090-fa  Tue Jul 12 14:29:31 2022 UTC  dump1090-fa 7.2 starting up.
12.07.22 16:29:31 (+0200)  dump1090-fa  rtlsdr: using device #0: Generic RTL2832U OEM (Realtek, RTL2838UHIDIR, SN 00000001)
12.07.22 16:29:31 (+0200)  dump1090-fa  Found Rafael Micro R820T tuner
12.07.22 16:29:31 (+0200)  dump1090-fa  rtlsdr: tuner gain set to 49.6 dB (gain step 28)
12.07.22 16:29:32 (+0200)  dump1090-fa  adaptive: using 50% duty cycle
12.07.22 16:29:32 (+0200)  dump1090-fa  adaptive: enabled adaptive gain control with gain limits 0.0dB (step 0) .. 58.6dB (step 29)
12.07.22 16:29:32 (+0200)  dump1090-fa  adaptive: enabled dynamic range control, target dynamic range 30.0dB
12.07.22 16:29:32 (+0200)  dump1090-fa  Allocating 4 zero-copy buffers
12.07.22 16:29:32 (+0200)  dump1090-fa  /start.sh: line 54:    12 Killed                  /usr/bin/dump1090-fa $dump1090configuration
12.07.22 16:30:38 (+0200)  dump1090-fa  Verifying settings...
12.07.22 16:30:38 (+0200)  dump1090-fa   
12.07.22 16:30:40 (+0200)  dump1090-fa  Receiver latitude is set: XX.XXX
12.07.22 16:30:40 (+0200)  dump1090-fa  Receiver longitude is set: XX.XXX
12.07.22 16:30:40 (+0200)  dump1090-fa   
12.07.22 16:30:40 (+0200)  dump1090-fa  Settings verified, proceeding with startup.
12.07.22 16:30:40 (+0200)  dump1090-fa   
12.07.22 16:30:40 (+0200)  dump1090-fa  Enabling adaptive gain in dynamic range mode.
12.07.22 16:30:40 (+0200)  dump1090-fa  Tue Jul 12 14:30:40 2022 UTC  dump1090-fa 7.2 starting up.
12.07.22 16:30:40 (+0200)  dump1090-fa  rtlsdr: using device #0: Generic RTL2832U OEM (Realtek, RTL2838UHIDIR, SN 00000001)
12.07.22 16:30:40 (+0200)  dump1090-fa  Found Rafael Micro R820T tuner
12.07.22 16:30:40 (+0200)  dump1090-fa  rtlsdr: tuner gain set to 49.6 dB (gain step 28)
12.07.22 16:30:41 (+0200)  dump1090-fa  adaptive: using 50% duty cycle
12.07.22 16:30:41 (+0200)  dump1090-fa  adaptive: enabled adaptive gain control with gain limits 0.0dB (step 0) .. 58.6dB (step 29)
12.07.22 16:30:41 (+0200)  dump1090-fa  adaptive: enabled dynamic range control, target dynamic range 30.0dB
12.07.22 16:30:41 (+0200)  dump1090-fa  Allocating 4 zero-copy buffers
12.07.22 16:30:41 (+0200)  dump1090-fa  /start.sh: line 54:    12 Killed                  /usr/bin/dump1090-fa $dump1090configuration
12.07.22 16:31:46 (+0200)  dump1090-fa  Verifying settings...
12.07.22 16:31:46 (+0200)  dump1090-fa   
12.07.22 16:31:48 (+0200)  dump1090-fa  Receiver latitude is set: XX.XXX
12.07.22 16:31:48 (+0200)  dump1090-fa  Receiver longitude is set: XX.XXX
12.07.22 16:31:48 (+0200)  dump1090-fa   
12.07.22 16:31:48 (+0200)  dump1090-fa  Settings verified, proceeding with startup.
12.07.22 16:31:48 (+0200)  dump1090-fa   
12.07.22 16:31:48 (+0200)  dump1090-fa  Enabling adaptive gain in dynamic range mode.
12.07.22 16:31:48 (+0200)  dump1090-fa  Tue Jul 12 14:31:48 2022 UTC  dump1090-fa 7.2 starting up.
12.07.22 16:31:48 (+0200)  dump1090-fa  rtlsdr: using device #0: Generic RTL2832U OEM (Realtek, RTL2838UHIDIR, SN 00000001)
12.07.22 16:31:49 (+0200)  dump1090-fa  Found Rafael Micro R820T tuner
12.07.22 16:31:49 (+0200)  dump1090-fa  rtlsdr: tuner gain set to 49.6 dB (gain step 28)
12.07.22 16:31:49 (+0200)  dump1090-fa  adaptive: using 50% duty cycle
12.07.22 16:31:49 (+0200)  dump1090-fa  adaptive: enabled adaptive gain control with gain limits 0.0dB (step 0) .. 58.6dB (step 29)
12.07.22 16:31:49 (+0200)  dump1090-fa  adaptive: enabled dynamic range control, target dynamic range 30.0dB
12.07.22 16:31:49 (+0200)  dump1090-fa  Allocating 4 zero-copy buffers
12.07.22 16:31:49 (+0200)  dump1090-fa  /start.sh: line 54:    13 Killed                  /usr/bin/dump1090-fa $dump1090configuration
12.07.22 16:32:55 (+0200)  dump1090-fa  Verifying settings...
12.07.22 16:32:55 (+0200)  dump1090-fa   
12.07.22 16:32:57 (+0200)  dump1090-fa  Receiver latitude is set: XX.XXX
12.07.22 16:32:57 (+0200)  dump1090-fa  Receiver longitude is set: XX.XXX
12.07.22 16:32:57 (+0200)  dump1090-fa   
12.07.22 16:32:57 (+0200)  dump1090-fa  Settings verified, proceeding with startup.
12.07.22 16:32:57 (+0200)  dump1090-fa   
12.07.22 16:32:57 (+0200)  dump1090-fa  Enabling adaptive gain in dynamic range mode.
12.07.22 16:32:57 (+0200)  dump1090-fa  Tue Jul 12 14:32:57 2022 UTC  dump1090-fa 7.2 starting up.
12.07.22 16:32:57 (+0200)  dump1090-fa  rtlsdr: using device #0: Generic RTL2832U OEM (Realtek, RTL2838UHIDIR, SN 00000001)
12.07.22 16:32:57 (+0200)  dump1090-fa  Found Rafael Micro R820T tuner
12.07.22 16:32:57 (+0200)  dump1090-fa  rtlsdr: tuner gain set to 49.6 dB (gain step 28)
12.07.22 16:32:58 (+0200)  dump1090-fa  adaptive: using 50% duty cycle
12.07.22 16:32:58 (+0200)  dump1090-fa  adaptive: enabled adaptive gain control with gain limits 0.0dB (step 0) .. 58.6dB (step 29)
12.07.22 16:32:58 (+0200)  dump1090-fa  adaptive: enabled dynamic range control, target dynamic range 30.0dB
12.07.22 16:32:58 (+0200)  dump1090-fa  Allocating 4 zero-copy buffers
12.07.22 16:32:58 (+0200)  dump1090-fa  /start.sh: line 54:    13 Killed                  /usr/bin/dump1090-fa $dump1090configuration
12.07.22 16:34:03 (+0200)  dump1090-fa  Verifying settings...
12.07.22 16:34:03 (+0200)  dump1090-fa   
12.07.22 16:34:05 (+0200)  dump1090-fa  Receiver latitude is set: XX.XXX
12.07.22 16:34:05 (+0200)  dump1090-fa  Receiver longitude is set: XX.XXX
12.07.22 16:34:05 (+0200)  dump1090-fa   
12.07.22 16:34:05 (+0200)  dump1090-fa  Settings verified, proceeding with startup.
12.07.22 16:34:05 (+0200)  dump1090-fa   
12.07.22 16:34:05 (+0200)  dump1090-fa  Enabling adaptive gain in dynamic range mode.
12.07.22 16:34:05 (+0200)  dump1090-fa  Tue Jul 12 14:34:05 2022 UTC  dump1090-fa 7.2 starting up.
12.07.22 16:34:06 (+0200)  dump1090-fa  rtlsdr: using device #0: Generic RTL2832U OEM (Realtek, RTL2838UHIDIR, SN 00000001)
12.07.22 16:34:06 (+0200)  dump1090-fa  Found Rafael Micro R820T tuner
12.07.22 16:34:06 (+0200)  dump1090-fa  rtlsdr: tuner gain set to 49.6 dB (gain step 28)
12.07.22 16:34:06 (+0200)  dump1090-fa  adaptive: using 50% duty cycle
12.07.22 16:34:06 (+0200)  dump1090-fa  adaptive: enabled adaptive gain control with gain limits 0.0dB (step 0) .. 58.6dB (step 29)
12.07.22 16:34:06 (+0200)  dump1090-fa  adaptive: enabled dynamic range control, target dynamic range 30.0dB
12.07.22 16:34:06 (+0200)  dump1090-fa  Allocating 4 zero-copy buffers
12.07.22 16:34:06 (+0200)  dump1090-fa  /start.sh: line 54:    13 Killed                  /usr/bin/dump1090-fa $dump1090configuration

**Comment by ketilmo** [comment]
Hi @SkyDiscovery,

Are your feeders identical in the setup? Same Pi model and dongle? If you can, I would try to swap the dongle with the working setup to see if that makes any difference. You could also try switching the PSU and writing a new memory card. Let us know if you can get it to work!

Kind regards,
Ketil
