### ISSUE TITLE
no ADS-B data program seen listening on port 30978

### ISSUE THREAD

**Issue by g0Idfinger** [ketilmo/balena-ads-b#75]
piaware keeps reporting this:
no ADS-B data program seen listening on port 30978

it never reports up any UAT traffic.  

Running pi3b with 2 SDRs configured.

**Comment by ketilmo** [comment]
Hi @g0Idfinger,

Thanks for reaching out. That log message might indicate that the dump978 service is not running. Do you see any log output from the `dump978-fa` service?

**Comment by ketilmo** [comment]
Hi @g0Idfinger,

Any update on this issue? Are you still having problems, or can this issue be closed?

**Comment by ketilmo** [comment]
Closing due to lack of feedback. Please reach out again if you are still having issues.

**Comment by serviceman77** [comment]
This is great work. I just built this on my Pi, and I am having the same issue as above. This is the piaware error. 
 piaware  attempting to start dump978.. 
 piaware  can't start dump978, no services that look like dump978 found
UAT_ENABLED	true All services are in my variables.
Radarbox is able to use the 978. Only piaware has this issue.
Thanks again

**Comment by ketilmo** [comment]
@serviceman77

**Comment by ketilmo** [comment]
Hi @serviceman77,

Thanks for reaching out. Can you please filter the logs on the dump978 service and see if you see any errors?

**Comment by serviceman77** [comment]
[Image.png]
It was empty when I first opened it. I restarted it and now I get some logs. RadarBox is receiving but FA does not. Thanks for looking into this. Added some screenshots from FA and RB
[Image.png]
[Image.png]

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by serviceman77** [comment]
![image](https://github.com/ketilmo/balena-ads-b/assets/166453764/c8f8c175-e123-4b23-b0b2-80f3ba430a44)

Radarbox
<img width="124" alt="image" src="https://github.com/ketilmo/balena-ads-b/assets/166453764/d0877c18-316e-4a25-8284-cbea8805dc78">

FlighyAware
<img width="208" alt="image" src="https://github.com/ketilmo/balena-ads-b/assets/166453764/8ed8c11a-e2fc-4495-aa4a-8658cdde1d8e">

**Comment by ketilmo** [comment]
Thank you so much for the images, @serviceman77!

I have located the problem and pushed for a fix. Can you update your installation to the latest version and report if it resolves the problem for you?

**Comment by serviceman77** [comment]
I am new to balena, how do I update?


________________________________

**Comment by ketilmo** [comment]
Check out the instructions here: https://github.com/ketilmo/balena-ads-b/?tab=readme-ov-file#part-14--updating-to-the-latest-version

If you deployed using the blue button, click it again, log in and then click the "use an existing fleet instead" option. Then, overwrite your current version. The settings variables will be preserved.

Don't hesitate to ask if you have more questions. Let me know how it goes.

**Comment by serviceman77** [comment]
The update has solved the issue! Thanks for your excellent work.

**Comment by ketilmo** [comment]
So glad to hear that, @serviceman77! Thanks for reporting back and confirming the fix. As I live in Norway and we don't have UAT rolled out here, it's quite hard to debug. So don't hesitate to reach out again in the future if you see other issues. Happy feeding!

Fixed by e4c81045961603a7b37a2e9ee8c4bdd5b1e4b540.
