### ISSUE TITLE
ADS-B stuck in online (VPN only) mode

### ISSUE THREAD

**Issue by Placemaster** [ketilmo/balena-ads-b#79]
I tried to update to the latest version of the supervisor version and also the host os version.
The host OS version updated without any problem. After that the system became stuck in online (VPN only) mode.
I could not find what to do to get the system running in normal state again.

As I have setup all the radars I do not want to start from scratch.

**Comment by ketilmo** [comment]
Hi @Placemaster,

It's great to hear that you were able to sort out this issue—also, a big thanks for sharing it with the community. That will make it easier for others facing this issue to resolve it independently. Happy flight feeding!
